const mongoose=require("mongoose");

const editprofileUser=mongoose.Schema({
    userid:{
        type:String,
        required:true
    },
    images:[{
        type:String,
     
    }],
    aboutme:{
        type:String,
        required:true
    },
    patnerpref:{
        type:String,
        required:true
    },
    isBlur:{
        type:Boolean,
        default:false
      },
      gender:{
        type:String,
        required:true,
      },
      phone:{
        type:String,
        required:true,
      },
      timeofbirth:{
      type:String,
      },
      placeofbirth:{
        type:String,
      },
      kundalidosh:{
        type:String,
      },
      martialstatus:{
        type:String,
        required:true,
      },
      profession:{
        type:String,
        required:true,
      },
      location1:{
        type:String,
      },
      city:{
        type:String,
        required:true,
      },
      state:{
        type:String,
        required:true,
      },
      country:{
        type:String,
        required:true,
      },
      religion:{
        type:String,
        required:true,
      },
      name:{
        type:String,
        required:true,
      },
      surname:{
        type:String,
        required:true,
      },
      lat:{
        type:Number,
      },
      lng:{
        type:Number,
      },
      diet:{
        type:String,
        required:true,
      },
      age:{
        type:String,
        required:true,
      },
      disability:{
        type:String,
        required:true,
      },
      puid:{
        type:String,
        required:true,
      },
      drink:{
        type:String,
        required:true,
      },
      education:{
        type:String,
        required:true,
      },
      height:{
        type:String,
        required:true,
      },
      income:{
        type:String,
        required:true,
      },
},{
    timestamps:true
   });

const EditProfiles=mongoose.model("editprofile",editprofileUser);
module.exports=EditProfiles;